name: Build and deploy JAR app to Azure Web App - WoofTalk

on:
  push:
    branches:
      - Aldair
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # Paso para listar el contenido del directorio WoofTalkv1
      - name: List files in WoofTalkv1 directory
        run: ls -la WoofTalkv1  # Verifica que el pom.xml esté aquí

      # Asegurarse de ejecutar Maven desde el directorio correcto
      - name: Build with Maven
        run: mvn clean install
        working-directory: WoofTalkv1  # Directorio correcto donde está el pom.xml

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'WoofTalkv1/target/*.jar'  # Asegúrate de que apunta al artefacto correcto

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'WoofTalk'
          slot-name: 'Production'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FFC1F93D7ACD4B99A4346D5DB781E0C9 }}
