name: Build and deploy JAR app to Azure Web App - WoofTalk

on:
  push:
    branches:
      - Aldair
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      # List files in the repository to verify file structure
      - name: List files in repository
        run: ls -la

      # List files in WoofTalkv1 directory to confirm pom.xml exists
      - name: List files in WoofTalkv1 directory
        run: ls -la WoofTalkv1

      # Build with Maven in the correct directory
      - name: Build with Maven
        run: mvn clean install
        working-directory: WoofTalkv1  # Confirming Maven works in the correct directory

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'WoofTalkv1/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      

